apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ghcr.io/thamyis100/order-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: AMQP_URL
              value: "amqp://guest:guest@rabbitmq:5672" # AMQP URL for RabbitMQ
